server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: prueba-service
          uri: lb://prueba-service
          predicates:
            - Path=/car/**
            - Path=/users/**
            - Path=/products/**
            - Path=/factura/**
        - id: entidades-service
          uri: lb://entidades-service
          predicates:
            - Path=/vehiculos/**
            - Path=/usuarios/**
            - Path=/tipo_vehiculo/**
            - Path=/roles/**
            - Path=/personas/**
            - Path=/paises/**
            - Path=/marca/**
            - Path=/inventario/**
            - Path=/factura/**
            - Path=/detalle_factura/**
            - Path=/departamento/**
            - Path=/continente/**
            - Path=/ciudad/**
