server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: prueba-service
          uri: lb://prueba-service
          predicates:
            - Path=/api/car/**
            - Path=/api/users/**
            - Path=/api/products/**
            - Path=/api/factura/**
        - id: entidades-service
          uri: lb://entidades-service
          predicates:
            - Path=/api/vehiculos/**
            - Path=/api/usuarios/**
            - Path=/api/tipo_vehiculo/**
            - Path=/api/roles/**
            - Path=/api/personas/**
            - Path=/api/paises/**
            - Path=/api/marca/**
            - Path=/api/inventario/**
            - Path=/api/factura/**
            - Path=/api/detalle_factura/**
            - Path=/api/departamento/**
            - Path=/api/continente/**
            - Path=/api/ciudad/**
