server:
  port: 8082
spring:
  cloud:
    config:
      server:
        git:
          default-label: develop
          uri: https://github.com/Juanfe2008/microservicio
          search-paths: config-data
  application:
    name: config-service
